#!/usr/bin/env python3
"""Convert ROS 2 ``.msg`` files into IDL files used by FastDDS/CycloneDDS.

This script is invoked from CMake (see ``RosMsgToIdl.cmake``) so that an
application can drop a ``Foo.msg`` next to its IDL files and have a matching
``Foo.idl`` produced automatically before ``fastddsgen``/``idlc`` runs.

The mapping follows the ROS 2 design (see ``rosidl_adapter``):

  bool      -> boolean
  byte      -> octet
  char      -> uint8
  float32   -> float
  float64   -> double
  int8/16/32/64    -> int8/16/32/64
  uint8/16/32/64   -> uint8/16/32/64
  string             -> string
  string<=N          -> string<N>
  wstring            -> wstring
  pkg/Type           -> pkg::msg::Type        (and adds an ``#include``)
  T[]                -> sequence<T>
  T[<=N]             -> sequence<T, N>
  T[N]               -> T values[N]           (fixed length array)

Constants (``type NAME = value``) are emitted as ``const`` declarations.
Default values are ignored (IDL has no portable equivalent).

The script is conservative: if the target ``.idl`` already exists *and* was
not produced by this script (no ``AUTOGENERATED FROM`` marker on its first
non-blank line), it is left untouched so hand-written IDL is never
clobbered.

Usage::

    msg_to_idl.py --package <pkg_name> [--out-dir <dir>] <msg_dir> [<msg_dir> ...]

When ``--out-dir`` is omitted, IDL files are written next to their source
``.msg`` files.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import List, Optional, Set, Tuple

AUTOGEN_MARKER = "// AUTOGENERATED FROM"

_PRIMITIVE_MAP = {
    "bool": "boolean",
    "byte": "octet",
    "char": "uint8",
    "float32": "float",
    "float64": "double",
    "int8": "int8",
    "uint8": "uint8",
    "int16": "int16",
    "uint16": "uint16",
    "int32": "int32",
    "uint32": "uint32",
    "int64": "int64",
    "uint64": "uint64",
    "string": "string",
    "wstring": "wstring",
}

# field line:  TYPE NAME [= DEFAULT]  (default is dropped)
_FIELD_RE = re.compile(
    r"^\s*([^\s#]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*(.+?))?\s*(?:#.*)?$"
)
# constant line: TYPE NAME=VALUE  (NAME must be ALL_CAPS to be considered a
# constant per ROS 2 .msg syntax)
_CONST_RE = re.compile(
    r"^\s*([^\s#]+)\s+([A-Z][A-Z0-9_]*)\s*=\s*(.+?)\s*(?:#.*)?$"
)


def _split_array_suffix(type_str: str) -> Tuple[str, Optional[str]]:
    """Split ``"int32[3]"`` -> ``("int32", "[3]")`` etc."""
    m = re.match(r"^(.+?)(\[[^\]]*\])$", type_str)
    if not m:
        return type_str, None
    return m.group(1), m.group(2)


def _split_string_bound(type_str: str) -> Tuple[str, Optional[int]]:
    """Split ``"string<=8"`` -> ``("string", 8)``."""
    m = re.match(r"^(w?string)<=(\d+)$", type_str)
    if not m:
        return type_str, None
    return m.group(1), int(m.group(2))


def _convert_base_type(
    type_str: str, default_pkg: str, includes: Set[str]
) -> str:
    """Map a ROS 2 base type (no array suffix) to IDL syntax."""
    base, bound = _split_string_bound(type_str)
    if base in ("string", "wstring") and bound is not None:
        return f"{_PRIMITIVE_MAP[base]}<{bound}>"

    if type_str in _PRIMITIVE_MAP:
        return _PRIMITIVE_MAP[type_str]

    # Foreign / same-package message reference.
    if "/" in type_str:
        pkg, name = type_str.split("/", 1)
    else:
        pkg, name = default_pkg, type_str

    if pkg == default_pkg:
        # Same-package: emit a sibling include so it resolves regardless of
        # the IDL include search-path layout.
        includes.add(f'#include "{name}.idl"')
    else:
        includes.add(f'#include "{pkg}/msg/{name}.idl"')
    return f"{pkg}::msg::{name}"


def _convert_field_type(
    type_str: str, default_pkg: str, includes: Set[str]
) -> Tuple[str, str]:
    """Return ``(idl_type, idl_array_suffix)`` for an IDL declaration."""
    base, suffix = _split_array_suffix(type_str)
    idl_base = _convert_base_type(base, default_pkg, includes)

    if suffix is None:
        return idl_base, ""

    inner = suffix[1:-1].strip()
    if inner == "":
        # Unbounded sequence
        return f"sequence<{idl_base}>", ""
    if inner.startswith("<="):
        bound = inner[2:].strip()
        return f"sequence<{idl_base}, {bound}>", ""
    # Fixed-size array
    return idl_base, f"[{inner}]"


def _convert_const_value(idl_type: str, raw: str) -> str:
    raw = raw.strip()
    if idl_type == "boolean":
        return "TRUE" if raw.lower() == "true" else "FALSE"
    return raw


def _detect_package(msg_path: Path, fallback: str) -> str:
    """Best-effort detection: ``<pkg>/msg/Foo.msg`` -> ``<pkg>``."""
    parts = msg_path.parts
    try:
        idx = parts.index("msg")
    except ValueError:
        return fallback
    if idx == 0:
        return fallback
    return parts[idx - 1]


def convert_msg(
    msg_path: Path, package: str
) -> str:
    """Convert a single ``.msg`` file's contents into IDL source text."""
    name = msg_path.stem
    text = msg_path.read_text(encoding="utf-8")

    includes: Set[str] = set()
    fields: List[str] = []
    consts: List[str] = []

    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue

        m_const = _CONST_RE.match(line)
        if m_const and "=" in line:
            ros_type, cname, value = m_const.group(1), m_const.group(2), m_const.group(3)
            idl_base, arr = _convert_field_type(ros_type, package, includes)
            if arr:
                # Constant arrays are not portable; skip.
                continue
            # CycloneDDS idlc rejects `const` declarations inside a `struct`.
            # Emit them at the enclosing `module msg { ... }` scope and prefix
            # with the struct name to avoid name clashes (matches the layout
            # used by upstream rosidl IDL output).
            const_type = "octet" if idl_base == "uint8" else idl_base
            consts.append(
                f"  const {const_type} {name}__{cname} = {_convert_const_value(idl_base, value)};"
            )
            continue

        m_field = _FIELD_RE.match(line)
        if not m_field:
            continue
        ros_type, fname, _default = m_field.group(1), m_field.group(2), m_field.group(3)
        idl_type, arr = _convert_field_type(ros_type, package, includes)
        fields.append(f"    {idl_type} {fname}{arr};")

    header = [
        f"{AUTOGEN_MARKER} {msg_path.name}",
        "// DO NOT EDIT - regenerated from the corresponding .msg file by msg_to_idl.py",
        "",
    ]
    if includes:
        header.extend(sorted(includes))
        header.append("")

    body = [f"module {package} {{", "  module msg {"]
    body.extend(consts)
    body.append(f"    struct {name} {{")
    body.extend(["  " + f for f in fields])
    body.extend(["    };", "  };", "};", ""])

    return "\n".join(header + body)


def _existing_is_autogen(idl_path: Path) -> bool:
    if not idl_path.exists():
        return True  # nothing to overwrite
    try:
        with idl_path.open("r", encoding="utf-8") as fh:
            for line in fh:
                stripped = line.strip()
                if not stripped:
                    continue
                return stripped.startswith(AUTOGEN_MARKER)
    except OSError:
        return False
    return False


def process_directory(
    msg_dir: Path,
    out_dir: Optional[Path],
    package: Optional[str],
) -> int:
    if not msg_dir.is_dir():
        return 0

    written = 0
    for msg_path in sorted(msg_dir.rglob("*.msg")):
        pkg = package or _detect_package(msg_path, msg_dir.parent.name)
        target_dir = out_dir if out_dir is not None else msg_path.parent
        target_dir.mkdir(parents=True, exist_ok=True)
        idl_path = target_dir / (msg_path.stem + ".idl")

        if not _existing_is_autogen(idl_path):
            print(
                f"[msg_to_idl] skip (hand-written exists): {idl_path}",
                file=sys.stderr,
            )
            continue

        new_text = convert_msg(msg_path, pkg)
        if idl_path.exists() and idl_path.read_text(encoding="utf-8") == new_text:
            continue
        idl_path.write_text(new_text, encoding="utf-8")
        print(f"[msg_to_idl] {msg_path} -> {idl_path}")
        written += 1
    return written


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--package",
        default=None,
        help="Force the IDL module/package name (otherwise inferred from path).",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory for generated .idl files (default: alongside .msg).",
    )
    parser.add_argument(
        "msg_dirs",
        nargs="+",
        help="One or more directories that contain .msg files (searched recursively).",
    )
    args = parser.parse_args(argv)

    out_dir = Path(args.out_dir).resolve() if args.out_dir else None

    total = 0
    for d in args.msg_dirs:
        total += process_directory(Path(d).resolve(), out_dir, args.package)
    print(f"[msg_to_idl] {total} file(s) generated/updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
