# cmake/RosMsgToIdl.cmake
#
# Provides ros_msg_to_idl_convert() which scans the given directories for
# ROS 2 .msg files and produces matching .idl files alongside them at
# CMake configure time. The companion script lives at:
#   apps/scripts/msg_to_idl.py
#
# Usage:
#   include(${CMAKE_CURRENT_SOURCE_DIR}/../cmake/RosMsgToIdl.cmake)  # adjust as needed
#   ros_msg_to_idl_convert(
#     PACKAGE   <package_name>            # optional; auto-detected from path
#     OUT_DIR   <directory>               # optional; defaults to .msg's dir
#     DIRS      <dir> [<dir> ...]
#   )
#
# Hand-written .idl files are never overwritten (the script keys off a
# leading "// AUTOGENERATED FROM" marker).

if(NOT DEFINED LWRCL_MSG_TO_IDL_SCRIPT)
  # This file lives in apps/cmake/, the script in apps/scripts/.
  get_filename_component(_lwrcl_msg_to_idl_dir
    "${CMAKE_CURRENT_LIST_DIR}/../scripts" ABSOLUTE)
  set(LWRCL_MSG_TO_IDL_SCRIPT "${_lwrcl_msg_to_idl_dir}/msg_to_idl.py"
      CACHE INTERNAL "Path to msg_to_idl.py")
endif()

function(ros_msg_to_idl_convert)
  cmake_parse_arguments(_RM2I "" "PACKAGE;OUT_DIR" "DIRS" ${ARGN})

  if(NOT _RM2I_DIRS)
    message(FATAL_ERROR "[ros_msg_to_idl_convert] DIRS is required")
  endif()

  if(NOT EXISTS "${LWRCL_MSG_TO_IDL_SCRIPT}")
    message(WARNING
      "[ros_msg_to_idl_convert] msg_to_idl.py not found at "
      "${LWRCL_MSG_TO_IDL_SCRIPT}; skipping .msg -> .idl conversion")
    return()
  endif()

  find_package(Python3 COMPONENTS Interpreter QUIET)
  if(Python3_Interpreter_FOUND)
    set(_py "${Python3_EXECUTABLE}")
  else()
    find_program(_py NAMES python3 python)
    if(NOT _py)
      message(WARNING
        "[ros_msg_to_idl_convert] python3 not found; skipping .msg -> .idl")
      return()
    endif()
  endif()

  set(_have_msg FALSE)
  foreach(_d IN LISTS _RM2I_DIRS)
    file(GLOB_RECURSE _msgs "${_d}/*.msg")
    if(_msgs)
      set(_have_msg TRUE)
      break()
    endif()
  endforeach()
  if(NOT _have_msg)
    return()
  endif()

  set(_args --)
  set(_extra)
  if(_RM2I_PACKAGE)
    list(APPEND _extra --package ${_RM2I_PACKAGE})
  endif()
  if(_RM2I_OUT_DIR)
    file(MAKE_DIRECTORY "${_RM2I_OUT_DIR}")
    list(APPEND _extra --out-dir "${_RM2I_OUT_DIR}")
  endif()

  message(STATUS "[ros_msg_to_idl] converting .msg in: ${_RM2I_DIRS}")
  execute_process(
    COMMAND "${_py}" "${LWRCL_MSG_TO_IDL_SCRIPT}" ${_extra} ${_RM2I_DIRS}
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE  _err)
  if(NOT _rc EQUAL 0)
    message(WARNING
      "[ros_msg_to_idl_convert] msg_to_idl.py exited ${_rc}\n"
      "stdout: ${_out}\nstderr: ${_err}")
  elseif(_out)
    message(STATUS "${_out}")
  endif()
endfunction()
